// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_tIHI_ICq27kHjrUFT7IAil_g6FO2-i0',
    appId: '1:555571648620:web:47be0af4f0e8ddc3f3e049',
    messagingSenderId: '555571648620',
    projectId: 'boutiquena-vendor-v2',
    authDomain: 'boutiquena-vendor-v2.firebaseapp.com',
    storageBucket: 'boutiquena-vendor-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx39AZUveYfNEr7YOy_KZdmm0kveAtgas',
    appId: '1:555571648620:android:abb115b2c5dab6e3f3e049',
    messagingSenderId: '555571648620',
    projectId: 'boutiquena-vendor-v2',
    storageBucket: 'boutiquena-vendor-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUr33S5H7y6tE1ABzcVl5Ma624euWk54',
    appId: '1:555571648620:ios:b80598cfce00f5cff3e049',
    messagingSenderId: '555571648620',
    projectId: 'boutiquena-vendor-v2',
    storageBucket: 'boutiquena-vendor-v2.firebasestorage.app',
    iosBundleId: 'com.example.boutiquenaVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBUr33S5H7y6tE1ABzcVl5Ma624euWk54',
    appId: '1:555571648620:ios:b80598cfce00f5cff3e049',
    messagingSenderId: '555571648620',
    projectId: 'boutiquena-vendor-v2',
    storageBucket: 'boutiquena-vendor-v2.firebasestorage.app',
    iosBundleId: 'com.example.boutiquenaVendor',
  );
}
